Add files via upload

diff --git a/dropbear-installer b/dropbear-installer
--- a/dropbear-installer
+++ b/dropbear-installer
@@ -1,23 +1,123 @@
 #!/bin/bash
+clear
+# Dropbear installer v2
+# CONFVPS
+# cores
 b="\033[1;37m"
 v="\033[1;32m"
 Ver="\033[1;31m"
-clear
+#
+if cat /etc/shells |grep "/bin/false" >/dev/null; then
+echo -n
+else
 echo "/bin/false" >>/etc/shells
+fi
 echo -e "\033[0m                \033[47;30m DROPBEAR INSTALLER\033[0m"
-echo ""
-echo -e ""$b"=========>>>"$v"ESCOLHA A PORTA"$b"<<<========"
-echo ""
-echo -e ""$b"[$v 1 $b]Porta:$Ver 443 
-$b[$v 2 $b]Porta:$Ver 80"
-echo -e ""$b
-read -p "Porta: " -e -i 443 porta
-clear
-case $porta in
-443)
-echo -e ""$b"ALTERANDO SSH..."
-sleep 1
-echo "Port 22
+echo ''
+echo -e '\033[1;37mAbaixo adicione uma porta para
+adicionar ao dropbear.'
+printf '\033[1;32mPorta: ';read porta
+if [[ -z "$porta" ]]; then
+  echo -e "\033[1;37mPorta invalida!"
+  sleep 1.5
+  echo -e "Saindo..."
+  sleep 1.5
+  exit 69
+fi
+if [[ "$porta" = '80' ]]; then
+	if [[ -f /etc/squid3/squid.conf ]]; then
+		echo -e "$Ver"'Squid3 instalado!'
+		echo ''
+		echo -e "$b""Para continuar com a instalacao\ndo dropbear na porta 80 tera que parar o squid3"
+		sleep 0.5
+		echo ''
+		read -p "Continuar? s/n: " re
+		if [[ "$re" = 's' ]]; then
+              echo -e "$v""Continuando..."
+              sleep  1
+              echo ''
+              echo -e "\033[1;37mParando squid3..."
+              service squid3 stop 1>/dev/null 2>/dev/null
+              sleep 1
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              echo -e "\033[1;37mInstalando dropbear..."
+              apt-get update 1>/dev/null 2>/dev/null
+              apt-get install dropbear -y 1>/dev/null 2>/dev/null
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              sleep 1
+              echo -e "\033[1;37mAdicionando porta..."
+              echo "NO_START=0" > /etc/default/dropbear
+              echo "DROPBEAR_PORT=80" >> /etc/default/dropbear
+              sleep 1
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              echo -e "\033[1;37mReniciando dropbear..."
+              service dropbear start 1>/dev/null 2>/dev/null
+              service dropbear restart 1>/dev/null 2>/dev/null
+              sleep 1
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              echo ''
+              echo -e "\033[1;37mInstalacao finalizada com sucesso."
+              exit 69
+    fi 
+    if [[ "$re" = 'n' ]]; then
+               echo -e ""$Ver"Saindo..."
+               sleep 1
+               exit 69
+    fi
+    fi
+    if [[ -f /etc/squid/squid.conf ]]; then
+		echo -e "$Ver"'Squid instalado!'
+		echo ''
+		echo -e "$b""Para continuar com a instalacao\ndo dropbear na porta 80 tera que parar o squid"
+		sleep 0.5
+		echo ''
+		read -p "Continuar? s/n: " rees
+		if [[ "$rees" = 's' ]]; then
+              echo -e "$v""Continuando..."
+              sleep  1
+              echo ''
+              echo -e "\033[1;37mParando squid..."
+              service squid stop 1>/dev/null 2>/dev/null
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              sleep 1
+              echo -e "\033[1;37mInstalando dropbear..."
+              apt-get update 1>/dev/null 2>/dev/null
+              apt-get install dropbear -y 1>/dev/null 2>/dev/null
+              sleep 1
+              echo -e "\033[1;37mAdicionando porta..."
+              echo "NO_START=0" > /etc/default/dropbear
+              echo "DROPBEAR_PORT=80" >> /etc/default/dropbear
+              sleep 1
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              echo -e "\033[1;37mReniciando dropbear..."
+              service dropbear start 1>/dev/null 2>/dev/null
+              service dropbear restart 1>/dev/null 2>/dev/null
+              sleep 1
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              echo ''
+              echo -e "\033[1;37mInstalacao finalizada com sucesso."
+              exit 69
+    fi
+    if [[ "$rees" = 'n' ]]; then
+               echo -e ""$Ver"Saindo..."
+               sleep 1
+               exit 69
+    fi
+    fi
+fi
+if [[ "$porta" = '443' ]]; then
+  if cat /etc/ssh/sshd_config |grep "443" >/dev/null; then
+    echo -e ""$Ver"Porta 443 esta adicionanda no sshd!"
+    echo ''
+    echo -e ""$b"Para continuar com a instalacao do dropbear
+    na porta 443teras que remover a porta 4443 do sshd"
+    echo ''
+    read -p "Continuar s/n: " ss
+      if [[ "$ss" = 's' ]]; then
+      	echo -e "$v""Continuando..."
+      	echo ''
+      	echo -e "\033[1;37mRemovendo porta do sshd..."
+      	echo "Port 22
 Protocol 2
 KeyRegenerationInterval 3600
 ServerKeyBits 1024
@@ -43,97 +143,53 @@ TCPKeepAlive yes
 AcceptEnv LANG LC_*
 Subsystem sftp /usr/lib/openssh/sftp-server
 UsePAM yes" > /etc/ssh/sshd_config
-echo -e "$b    [$v OK $b]"
-sleep 1
-echo -e ""$b"INSTALANDO DROPBEAR..."
-apt-get install dropbear -y 1>/dev/null 2>/dev/null
-echo -e "$b    [$v OK $b]"
-echo -e ""$b"ALTERANDO DROPBEAR..."
-sleep 1
+        sleep 1
+        echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+        echo -e "\033[1;37mReniciando openssh..."
+        service ssh restart >/dev/null 2>/dev/null
+        sleep 1
+        echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+        echo -e "\033[1;37mInstalando dropbear..."
+        apt-get update 1>/dev/null 2>/dev/null
+        apt-get install dropbear -y 1>/dev/null 2>/dev/null
+        sleep 1
+        echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+        echo -e "\033[1;37mAdicionando porta..."
 echo "NO_START=0" > /etc/default/dropbear
 echo "DROPBEAR_PORT=443" >> /etc/default/dropbear
-echo -e "$b    [$v OK $b]"
-sleep 1
-echo -e ""$b"RENICIANDOS SERVICOS..."
-service ssh restart 1>/dev/null 2>/dev/null
-service dropbear restart 1>/dev/null 2>/dev/null
-echo -e "$b    [$v OK $b]"
-sleep 1
-echo -e ""
-echo -e ""$b"SUCESSO! TUDO TERMINADO"
-;;
-80)
-echo -e "             "$ver$b"======>>>"$Ver"AVISO"$b"<<<======"
-echo ""
-echo -e ""$b"Ao instalar dropbear na porta 80 o squid sera parado\ncaso voce tenha ele instalado"
-echo ""
-sleep 1
-read -p "Deseja continuar? : [ s/n ] " -e -i n sim
-clear
-if [ "$sim" = "s" ];then
-echo ""
+        sleep 1
+        echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+        echo -e "\033[1;37mReniciando dropbear..."
+        service dropbear restart 1>/dev/null 2>/dev/null
+        sleep 1
+        echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+        echo ''
+        exit 69
+    else
+    	echo -e -n ""
+    fi
+    if [[ "$ss" = 'n' ]]; then
+    	echo -e ""$Ver"Saindo..."
+        sleep 1
+    	exit 69
+    fi
 fi
-if [ "$sim" = "n" ];then
-echo -e "VOLTANDO AO MENU..."
-sleep 2
-CONFVPS
 fi
-echo -e ""$b"PARANDO SQUID..."
-service squid3 stop 1>/dev/null 2>/dev/null
-service squid stop 1>/dev/null 2>/dev/null
-sleep 1
-echo -e "$b    [$v OK $b]"
-sleep 1
-echo -e ""$b"ALTERANDO SSH..."
-sleep 1
-echo "Port 443
-Port 22
-Protocol 2
-KeyRegenerationInterval 3600
-ServerKeyBits 1024
-SyslogFacility AUTH
-LogLevel INFO
-LoginGraceTime 120
-PermitRootLogin yes
-StrictModes yes
-RSAAuthentication yes
-PubkeyAuthentication yes
-IgnoreRhosts yes
-RhostsRSAAuthentication no
-HostbasedAuthentication no
-PermitEmptyPasswords no
-ChallengeResponseAuthentication no
-PasswordAuthentication yes
-X11Forwarding yes
-X11DisplayOffset 10
-PrintMotd no
-PrintLastLog yes
-TCPKeepAlive yes
-#UseLogin no
-AcceptEnv LANG LC_*
-Subsystem sftp /usr/lib/openssh/sftp-server
-UsePAM yes" > /etc/ssh/sshd_config
-echo -e "$b    [$v OK $b]"
-sleep 1
-echo -e "INSTALANDO DROPBEAR..."
-sleep 1
-apt-get install dropbear -y 1>/dev/null 2>/dev/null
-echo -e "$b    [$v OK $b]"
-sleep 1
-echo -e "ALTERANDO DROPBEAR..."
-sleep 1
-echo "NO_START=0" > /etc/default/dropbear
-echo "DROPBEAR_PORT=80" >> /etc/default/dropbear
-echo -e "$b    [$v OK $b]"
-sleep 1
-echo -e "RENICIANDOS SERVICOS..."
-sleep 1
-service ssh restart 1>/dev/null 2>/dev/null
-service dropbear restart 1>/dev/null 2>/dev/null
-echo -e "$b    [$v OK $b]"
-sleep 1
-echo -e ""
-echo -e "SUCESSO! TUDO TERMINADO"
-exit
-;;
-esac
+ echo -e "\033[1;37mInstalando dropbear..."
+              apt-get update 1>/dev/null 2>/dev/null
+              apt-get install dropbear -y 1>/dev/null 2>/dev/null
+              sleep 1
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              echo -e "\033[1;37mAdicionando porta..."
+              echo "NO_START=0" > /etc/default/dropbear
+              echo "DROPBEAR_PORT=$porta" >> /etc/default/dropbear
+              sleep 1
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              echo -e "\033[1;37mReniciando dropbear..."
+              service dropbear start 1>/dev/null 2>/dev/null
+              service dropbear restart 1>/dev/null 2>/dev/null
+              sleep 1
+              echo -e ""$b"["$v"OK"$b"]$b Sucesso..."
+              echo ''
+              echo -e "\033[1;37mInstalacao finalizada com sucesso."
+              exit 69
